words:
  блять: бвять :3
  бля: uwu~ бвя
  сука: сюка >_<
  хуй: буй~
  уёбок: увёбик
  пидор: няшка
  хуя: увя~
  ебать: вевать uwu~
  пиздец: uwu пивдей~
  ебу: uwu~
  ебан: uwuн~
  еблан: милашка
  хуе: uwe~
  сво: §l§o§4С§9В§fО§r
  z: §4Z
  v: §9V
diseases:
  - CBO